name: Bump version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: $()
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Set env
      run: echo ::set-env name=TAG::$(git describe --tags `git rev-list --tags --max-count=1`)

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        echo ${TAG}
        pip install bump2version
        TAG=$(git describe --tags `git rev-list --tags --max-count=1`)

    - name: Bump version (patch)
      if: contains(github.event.head_commit.message, '#patch')
      run: |
        VERSION=$(python -c "import xyztest; print(xyztest.__version__)")
        bump2version --current-version $VERSION patch xyztest/__init__.py

    - name: Bump version (minor)
      if: contains(github.event.head_commit.message, '#minor')
      run: |
        VERSION=$(python -c "import xyztest; print(xyztest.__version__)")
        bump2version --current-version $VERSION minor xyztest/__init__.py

    - name: Bump version (major)
      if: contains(github.event.head_commit.message, '#major')
      run: |
        VERSION=$(python -c "import xyztest; print(xyztest.__version__)")
        bump2version --current-version $VERSION major xyztest/__init__.py

    - name: Commit files
      if:
        contains(github.event.head_commit.message, '#patch') ||
        contains(github.event.head_commit.message, '#minor') ||
        contains(github.event.head_commit.message, '#major')        
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        # If secrets.GITHUB_TOKEN is used, "Publish to PyPI" action will not be triggered
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: none
