name: 🏃 Ubuntu

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]
        operating-system: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Make cache folder if not exists
        run: mkdir -p ~/conda_pkgs_dir

      - name: Cache conda
        uses: actions/cache@v1
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-testenv-${{ hashFiles('conda-linux-64.lock') }}
          restore-keys: |
            ${{ runner.os }}-conda-testenv-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
          $CONDA/bin/conda config --set use_only_tar_bz2 true

      - name: Install dependencies
        run: |
          conda create --name testenv --file conda-linux-64.lock

      - name: Test explicit env
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          conda info
          conda list
