name: 🏃 Windows

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]
        operating-system: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/Scripts >> $GITHUB_PATH

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0  # increase value -> force reset cache
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('**/conda_requirements.txt') }}

      - name: Install dependencies
        run: |
          conda create --name testenv --file conda-win-64.lock

      - name: Test explicit env
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          conda info
          conda list
